version: '3.9'

services:
  server:
    container_name: mock-server
    image: mock-server:latest
    ports:
      - "80:80"
      - "443:443"
    privileged: true
    volumes:
      - ./tmp:/tmp
    environment:
      - DOCKER_API_VERSION=1.41 
